# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170529_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conexion', models.CharField(max_length=100)),
                ('ultimaconexion', models.CharField(max_length=100)),
                ('apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apps')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='tiempo',
        ),
    ]
