# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170529_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.CharField(max_length=100),
        ),
    ]
