# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170601_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='iduser',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
