# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170601_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='ident',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
